// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type OrderInput struct {
	Name  string `json:"Name"`
	Desc  string `json:"Desc"`
	Image string `json:"Image"`
}

type UserInput struct {
	Name string `json:"Name"`
	Age  int    `json:"Age"`
}
