name: Deploy Go Backend

on: 
  push:
    branches:
      - deploy

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1

      - name: Install dependencies
        working-directory: ./Go-Backend
        run: | 
          go get github.com/gin-gonic/gin
          go get gorm.io/gorm
          go get github.com/mattn/go-sqlite3
          go build -o Go-REST-Backend .
